muccg/rdrf

rdrf/runtime-requirements.txt
Upgrade path for mongo.
https://api.mongodb.com/python/2.9/changelog.html
https://api.mongodb.com/python/2.9/migrate-to-pymongo3.html
Checked the migration path, none of the deprecated api in the code base.
=> RDR-1350 pymongo 2.9.3

docker-entrypoint.sh, rdrf/rdrf/settings.py, rdrf/runtime-requirements.txt
django-secure was deprecated in Django 1.8 and the functionality is now core Django.
=> Rdr 1357 deprecate django secure

uwsgi/docker.ini, uwsgi/vassals/socket-9100.ini
For an explanation of what lazy-apps does, see:
https://uwsgi-docs.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html#preforking-vs-lazy-apps-vs-lazy
By default, uwsgi loads the state of the app, including all libraries,
and then forks. This causes problems for some libraries, such as
SQLAlchemy:
https://stackoverflow.com/questions/22752521/uwsgi-flask-sqlalchemy-and-postgres-ssl-error-decryption-failed-or-bad-reco
To play it safe, we should enable lazy-apps.
=> enable lazy-apps uwsgi option

docker-entrypoint.sh
=> Shell linting

rdrf/rdrf/models.py
Issue here is that strings in cdes with datatype has the Txxxxx time part
The display value of the field was erroring , return empty string
The temporary report datatable inserts display values 
The fix was to parse these full date time strings correctly 
I've tested locally with both types of date strings
=> rdrf #391 correctly parse dates for reports

rdrf/rdrf/dynamic_data.py, rdrf/rdrf/features/fh_file_upload.feature, rdrf/rdrf/features/steps.py, rdrf/rdrf/file_upload.py, rdrf/rdrf/filestorage.py, rdrf/rdrf/form_view.py, rdrf/rdrf/registry_specific_fields.py, scripts/old/patient_importer.py
File CDEs allow a file to uploaded.
When uploaded a download  link should appear at the file cde location.
An uploaded file can be replaced by uploading another file.
An uploaded file can be deleted by checking a "clear" checkbox near the file link - when checked , the file storage module deletes the file.
Changes have been made to the underlying file storage mechanism which resulted in several issues 
The file link for a download was not displaying in the view's post response. ( this was a logic error in the view not the file storage change: the "wrapping" of file widgets was occurring too early so that no upload ids had been created at that stage) The fix was to do recreate the wrapped section forms at a later stage when the upload ids had been generated.
The clear checkbox didn't work …
=> File link display+ tests 

rdrf/rdrf/dynamic_data.py, rdrf/rdrf/features/fh_file_upload.feature, rdrf/rdrf/features/fh_multisection_tests.feature, rdrf/rdrf/features/steps.py, rdrf/rdrf/features/utils.py, rdrf/rdrf/file_upload.py, rdrf/rdrf/form_view.py
Items ( blocks of CDEs) in a multisection can be "marked for deletion" and then the form saved, causing the entire block of cdes ( form in a formset)  to be deleted - this has the effect of changing the indices of the items. In order to correctly display file links for file cdes on cdes which have not been uploaded in the POST ( but have in earlier POSTS) - values of the uploaded file django ids for the cde need to be retrieved but IF items have been marked for deletion ( and deleted in the current POST) the cde values from the correct index needs to be loaded prior to the record being saved
An "index map" of new indices to old indices after a deletion was introduced to enable this , but it wasn't being correctly threaded some of the refactored code for the file storage code resulting in …
=> Mark for deletion

rdrf/rdrf/consent_forms.py, rdrf/rdrf/form_view.py
We'd  removed a redirect to fix another issue ( success message not appearing.)
I put back the redirect and created the success message in the correct way.
I have refactored slightly to make clearer ( no context dictionary needs to be created if the form is valid)
=> Consent View fixes

rdrf/rdrf/generalised_field_expressions.py, scripts/import_multisection_data.py
Added import_multisection_data.py script 
usage:
python /app/scripts/import_multisection_data.py mapfile csvdatafile  > logfile
The mapfile looks like:
old id1,rdrf id1
old id2,rdrf id2
old id3>,rdrf id3
and is a by product of the original fh data import
csv data file was created by exporting from the returned spreadsheet Jing provided ( we gave them a format.)
All the script does is update multi-section data in the genetic data form. No attempt to generalise it has been made but we could adapt very easily to create a generic importer as the script merely calls into an existing "field expression" parser which was previously written  for reports (get) and questionnaire updating (set.)
=> Fh multisectionimport

rdrf/rdrf/form_view.py, rdrf/rdrf/questionnaires.py, rdrf/rdrf/templates/rdrf_cdes/questionnaire.html
Adding items to a multisection was working before but adding dynamicallly and then removing added items within the mulitsection had multiple issues fixed in this PR ( NB. has already been fixed in the clinical forms but was overlooked in the questionnaire till now)
- adding followed by remove  doesn't garble the cdes in the item anymore
- ditto persists to new  patient ok 
- ditto updates ok to existing peatient
Also cosmetically the seperator between added items now appears consistently for all items
Additionally the "mark item for deletion" checkbox has been removed as it makes no sense on the questionnaire as all items are new and the form is only filled out once
=> Fixes to questionnaire multisection behaviour

rdrf/rdrf/contexts_api.py, rdrf/rdrf/generalised_field_expressions.py, scripts/cdeimport.py, scripts/fh3_import.py
usage:
```bash
python /app/scripts/cdeimport.py <registry code> <field map file> <id map file> <data file csv>   > results.log
```
where
field map is a csv mapping the "field numbers" we provided the client to form name, section code, cde codes in the registry
id map is a mapping csv file of the client's "id for patients" to our id
( hence this is an updater and relies on the patient already having an id in rdrf )
The script updates any cde values and assumes the first item of a multisection is being updated ( for fh the biochemistry profile. )
The script runs each patient update in its own transaction  and rolls back on any unhandled error.
Produces a log of each update ( any "bad" values which are not "empty" /unfilled in values from the csv are logged
Then a set of stats is printed at …
=> Script for third FH data import

rdrf/rdrf/templates/rdrf_cdes/base_questionnaire.html, rdrf/rdrf/templates/rdrf_cdes/questionnaire.html
If there are required field errors, the error is scrolled to automatically.
The missing address field errors  outlined in red ( same styling as the consent validation) and scrolled to.
Instead of the red table row for required fields I've made the questionnaire use red asterisks ( as we use in the application.)
=> Questionnaire Validation Improvements

rdrf/rdrf/urls.py, rdrf/tasks.py
Recently added tasks.py was triggering django initialisation, which is not what we want in prod. Initialisation of Django needs to take place in the web app.
=> don't initialise django app within tasks.py

rdrf/rdrf/auth.py, rdrf/rdrf/urls.py
Addresses muccg/rdrf-ccg#940 partially, started a discussion on the rest of that issue.
This one just changes the invalid login message a bit to warn users that their account will be locked after `LOGIN_FAILURE_LIMIT` incorrect attempts.
=> Changing login incorrect msg to warn users they will be locked out. #940

rdrf/rdrf/components.py, rdrf/rdrf/models.py, rdrf/rdrf/patients_listing.py, rdrf/rdrf/rpc_commands.py, rdrf/rdrf/templates/rdrf_cdes/form_group_button_component.html, rdrf/rdrf/templates/rdrf_cdes/forms_button.html, rdrf/rdrf/templates/rdrf_cdes/patients_listing.html
Current patient listing is very slow ( most noticeably in FH). The main cause is the retrieval of the forms list dropdown for each patient on the page. I have moved this logic into an ajax call so the forms list is rendered on demand. This has reduced  the page load time by a factor 11-12 in my testing with a db of 50000 dummy patients.
The forms list itself has been enhanced slightly: Currenly for FH, say, all folllow ups are shown in a list. The new implementation shows the latest 10. Also an "Add Follow Up" link has been appended to the list allowing easy updating of a patient record resulting from a search. I've toned down the colour to make it less garish also.
=> Ajax patient listing

rdrf/rdrf/forms/progress/form_progress.py, rdrf/rdrf/views/patients_listing.py
Form progress is a notion we introduced trying to emulate some ophg requirements.
Forms have "completion cdes"  - which affect the percentages for form progress - but we didn't modify the calculation when we introduced the notion of "patient type" for MTM. This ticket addresses this.
=> mtm #281 form progress when there are patient_types

rdrf/registry/patients/admin_forms.py
Our normal "business rules" do not allow users in one working group to edit the details of patient in another working group, 
The clinician selection form allows choice of a clinician - but it also indirectly causes the working group of the patient to match that of the clinician.
Hence if a parent self-patient user changes their own clinician ( or their child''s), the working group of the parent user can diverge from the child's.
This fix allows the parent user to edit the child's demographic form despite being in a different working group. The working group itself is not editable by the parent.
=> Parent child working group handling

rdrf/rdrf/admin.py, rdrf/rdrf/settings.py, rdrf/setup.py
Adding reversion module in our application.
Apply reversion on ClinicalData model so that the model can have history of changes. This enables the Admin user to revert back to any older version.
The reversion for ClinicalData is applied at Admin level.
=> rdrf #590 added django reversion on ClinicalData model

rdrf/rdrf/helpers/utils.py, rdrf/rdrf/views/actions.py
Allow universal links which when browsed to redirect the user the correct view.
E.g.
site/actions?action=form&form=SomeFormName&registry=ang
or
site/actions?action=form&form=SomeFormName&registry=ang&id=23
where id is the patient id
Checks user has access to the page before redirecting
Deduces the child for parent guardian users
If the user is a patient ( for registries that allow this) , the deduced patient also
=> angelman #312 universal link allows id

rdrf/rdrf/forms/widgets/widgets.py
A regular expression were looking for selected="selected" in order
to replace the select by a label. However, as mentioned in Django doc,
boolean selected is prefered HTML5 compare to selected="selected".
I am guessing Django changed the Select widget html in the latest 2.1 version.
=> #836 ReadOnlySelect widget was broken by last Django update

rdrf/registry/groups/admin_forms.py
Note there are two issues:
* first the class UserChangeForm is  replacing the base Django UserChangeForm class
in order to add support for workinggroups and registry fields. If at the time of the
decision it was ok, since Django likely updated the Django UserChangeForm and so we
are losing the new code from Django. Probably introducing other bug (.i.e some code is
related to user permission in the Django UserChangeForm). An alternative solution is likely to extend
the base function instead to override it.
* the password reset page has the default Django UI theme - I guess it has always been the
case.
=> #846 fix the reset password link

rdrf/setup.py
The django-useraudit last version includes the fix for the user reactivate feature #837
=> #869 bump django-useraudit version

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx, rdrf/rdrf/models/proms/models.py
Note: we also fixed a bug with the survey question clean() function crashing when the instructions
were empty.
=> #861 update proms consent checkbox confirmation text

rdrf/rdrf/models/proms/models.py, rdrf/rdrf/services/rest/auth.py, rdrf/rdrf/services/rest/views/proms_api.py
Nginx was eating the custom header secret token. We don't want to
depend from Nginx configuration (neither Nginx configuration mention the
secret_token existence) so we will sent the secret token through
the POST variable..
=> #852 do not send secret token in the header

rdrf/rdrf/db/dynamic_data.py, rdrf/rdrf/management/commands/update_calculated_fields.py, rdrf/registry/patients/models.py
Problem: the django admin update_Calculated_fields is crashing on staging as
it is calling save_form_value which load all dynamic data and save them all.
The problem been that some key (form__section_cdecode) do not exist, the form name
having changed. When saving the dynamic data, it crashes as the key does not exist.
To solve the issue we add a new parameter ignoring the not existing keys.
=> issue #897 - update_calculated_fields crashes on unexisting key

rdrf/rdrf/admin.py
The html of the resend button was displayed instead of the button itself.
=> #906 fix resend notification link

rdrf/rdrf/services/io/reporting/reporting_table.py
It takes about twice less time to execute the report for 10K inserts (staging data).
=> #936 report: do one bulk insert instead of multiple inserts

rdrf/rdrf/services/rest/views/proms_api.py
for example, an admin creates two surveys and send the two links. But the second survey is answered first (as the user will read it first), then the user answers the first survey link. Obviously we want to keep the latest answered survey. So we need to sort by updated time.
=> #932 pull_proms: sort by updated date to avoid overwriting the most recently answered 

rdrf/rdrf/testing/unit/tests.py, rdrf/registry/groups/models.py
This fix is a little between two chairs:
- it works by checking if the parent_view module exists which I think is an ok check.
- however it hardcodes angleman module location because the parent_view module is in the angelman part, not in rdrf.
PS: tested on rdrf and Angelman. On Angelman the parent login unit test is executed and the is_parent() function is executed too.
=> #959 ignore is_parent for anything else than angelman

rdrf/rdrf/helpers/utils.py, rdrf/rdrf/management/commands/update_calculated_fields.py
Otherwise exceptions would not be logged when running update_calculated_fields with django-admin command line.
=> #905 catch and log exceptions from update_calculated_fields

rdrf/rdrf/services/rest/views/api_views.py
The API call was crashing when the user sent a wrong country code (XX). We were receiving notification.
Note: we could not identified why the user sent wrong XX country code. We suspect that the user, using the Chrome 42 Android 6.0 (Nexus 5S), has an obsolete javascript engine behaving weirdly.
=> #1062 registration: fix api call to get subdivision

rdrf/explorer/models.py, rdrf/explorer/views.py, rdrf/rdrf/helpers/utils.py
all queries must start with: "SELECT p.id" ( this is required to make the report work anyway)
"DELETE " must not be in the clause
"UPDATE " must not be the clause
"DROP " must not be in the clause
=> #976 explorer: harden reporting interface

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
a) ignore Return key (do not reload the survey)
b) display the previous text input value when pressing Previous button
=> #1079 proms text input: ignore Return key + display previous value

rdrf/rdrf/frontend/package.json, rdrf/rdrf/frontend/watch.js, rdrf/rdrf/frontend/yarn.lock
watch.js was not building the Proms JS/CSS static files when loading the site for the first time in development environment (it was rebuilding them as soon as one file was changed in frontend/src folder - so we did not detect the problem earlier)
=> #1110 auto build of Proms JS/CSS file in dev environment

rdrf/rdrf/models/definition/models.py
The validation that checks "." in CDE name was commented out.
With this change, the workflow was tested as described in the ticket.
=> rdrf #1289 CDE labels can't have period

rdrf/rdrf/testing/behaviour/features/ciccrc_general.feature, rdrf/rdrf/testing/behaviour/features/ciccrc_navigate.feature, rdrf/rdrf/testing/behaviour/features/steps.py
Removed previous step for checking PROMS options and replaced with new step.
- The previous step was not very transparent; It was not clear what the expectation of the step was by reading the feature file, hence the new step is more explicit.
- Two separate steps were able to be combined into one; The first capture group defines which menu is examined. The menu title is used to define which.
- The feature `ciccrc_general.feature` was modified, as opposed to creating a new feature; This is partly because this feature already tests the PROMS options, but it was also necessary to modify the feature to remove a reference to the previous step.
=> rdrf #1305 New step and modified feature for checking PROMS options

rdrf/rdrf/context_processors/context_processors.py, rdrf/rdrf/settings.py, rdrf/rdrf/templates/two_factor/_wizard_actions.html
Cancel link on 2fa page of PROMS system was poining to the url 'patientlisting' which is not exposed in PROMS. As a fix, the Cancel link was made to point to 'logout' url iconditionally (only if it is a PROMS system else will point to 'patientlisting' url)
This condition assumes that PROMS system has the env varibale SYSTEM_ROLE set to SystemRoles.CIC_PROMS
=> rdrf #1299 2fa page cancel url modified

rdrf/rdrf/auth/forms.py, rdrf/rdrf/urls.py
- The url conf was modified to match the new django version.
- The NoReverseMatch issue for password_assistance_confirm url was fixed (The kwargs of the url was expecting a string ```P<uidb64>[0-9A-Za-z_\-]+``` but the context had byte array values like ```b'Mw'```)
=> rdrf #1308 Password reset email not sent

rdrf/rdrf/auth/__init__.py, rdrf/rdrf/auth/forms.py
The MTM Curator users were not allowed to reset password when they get locked out (due to wrong password attempts). Instead, they used to get an email with instruction to contact admin.
This was fixed in this by allowing Curator users to set a new password when they get locked out.
They get an email with a secure password reset link when they submit their email from the password_assistance form.
[password_workflow_before.pdf](https://github.com/muccg/rdrf/files/4686580/password_workflow_before.pdf)
[password_workflow_after.pdf](https://github.com/muccg/rdrf/files/4686578/password_workflow_after.pdf)
=> rdrf #1327 workflow for curators added for resetting password

rdrf/rdrf/models/proms/models.py
If the survey's display name is missing, a validation error is raised.
=> rdrf #1370 If the display name is missing, a validation error is raised

rdrf/rdrf/frontend/src/pages/proms_page/logic.ts, rdrf/rdrf/models/proms/models.py
Multiselect cdes have been used as preconditions in Breast cancer:
If a multiselect has value [a,c] and the precondition value is c the expression evaluated is: does [a,c] include c ( true )
=> rdrf #1427 added contains operator for preconditions

rdrf/rdrf/models/proms/models.py
- template_data includes survey_name variable that was set to name of survey
- changed this to display_name instead
=> rdrf #1114 SurveyRequest email template_data modified

scripts/export_zip.sh
- Assumes that the local version of staging has been prepared.
- Exports .zip to `data/dev/`
Closes #1475.
=> rdrf #1475 Short script to export registry .zip, assuming local prepared

rdrf/rdrf/models/definition/models.py
- prevented a ContextFormGroup of type 'M' having multiple forms in it
=> rdrf #1281 Validation added for ContextFormGroup type Multiple

rdrf/rdrf/testing/behaviour/features/steps.py
`steps.py` -- `menu_contains` and `menu_not_contains`;
- Altered method of capturing data to check, from `.get_attribute('innerHTML')` to `.get_attribute('text').strip()`.
- Xpath not changed.
Closes #1517.
=> rdrf #1517 Altered broken menu check steps

rdrf/setup.py
Upgraded django-ajax-selects==1.9.1 from 1.7.1
Parent: #1529
=> rdrf #1536 Upgraded django-ajax-selects from 1.7.1 to 1.9.1

rdrf/rdrf/testing/behaviour/features/ciccrc_menu.feature
Removed checks for the Deidentified Report menu option from `rdrf/rdrf/testing/behaviour/features/ciccrc_menu.feature`.
=> rdrf #1568 Removed Deidentified Report references from feature files

rdrf/rdrf/models/definition/models.py, rdrf/rdrf/services/io/actions/deidentified_data_extract.py
The deidentified report now interprets  a "blacklist" key in the custom action data textfield (json) as a list of form names to not include in the report.
=> rdrf #1597 blacklist on deidentified data extract

rdrf/setup.py
Django has been successfully upgraded to the latest patch release (2.2.16).
=> rdrf #1607 Updated Django to 2.2.16

rdrf/rdrf/forms/widgets/widgets.py, rdrf/setup.py
Updated pycountry from 19.8.18 to 20.7.3, and added exception handling to `rdrf/rdrf/forms/widgets/widgets.py` to account for a LookupError now thrown when the subdivision is left blank.
=> rdrf #1614 Updated pycountry dependency & added exception handling for LookupError

rdrf/rdrf/testing/behaviour/features/fh_add_patient_empty_address_country.feature, rdrf/rdrf/testing/behaviour/features/steps.py
Added new step to `steps.py` to check for alert message boxes, and new feature `fh_add_patient_empty_address_country.feature` to test said step by checking for the error alert message when attempting to save a patient address without entering the country.
=> rdrf #1618 Added feature to test for missing country & step to check for alert boxes

rdrf/rdrf/models/definition/models.py, rdrf/rdrf/templates/admin/change_form.html, rdrf/rdrf/templates/admin/rdrf/commondataelement/change_form.html
Added `get_val_description` method to the `CommonDataElement` class in models.py, which is used in rdrf/rdrf/templates/admin/rdrf/commondataelement/change_form.html to display the validation rules currently set for the CDE on the CDE admin page.
=> Rdrf #1603 Validation rules description added to CDE admin page

rdrf/rdrf/__init__.py, rdrf/rdrf/templates/admin/rdrf/commondataelement/change_form.html, rdrf/rdrf/templates/rdrf_cdes/base.html, rdrf/rdrf/testing/behaviour/features/base_cde_page_validators.feature, rdrf/rdrf/testing/behaviour/features/steps.py, rdrf/setup.py
Added new script to `change_form.html` for the CDE creation admin page that hides and clears validators not used by the selected data type, as well as `base_cde_page_validators.feature` and the requisite steps in `steps.py` to perform automated tests of the script's functionality.
=> Rdrf #1627 Added dynamic validation field display for CDE creation admin page

rdrf/rdrf/testing/behaviour/features/ciccrc_passwordreset.feature, rdrf/rdrf/testing/behaviour/features/steps.py
Added new steps to `steps.py` and created `ciccrc_passwordreset.feature` to test that the workflow for sending an email to reset a user's password progresses as expected and causes no run-time errors.
=> Rdrf #1625 Added password reset workflow test

rdrf/rdrf/views/family_linkage.py
Updated family_linkage.py to not try and use patient IDs for non-patient relatives when changing a relative patient to an index patient.
=> rdrf #1654 Updated family_linkage.py to fix non-patient relative issues

docker-compose-common.yml, rdrf/rdrf/services/rest/serializers.py, rdrf/rdrf/services/rest/urls/api_urls.py
Both the Genes and Laboratories API views have been de-registered. The Clinicians API view will now only be registered if the system is non-CIC.
=> Rdrf #1690 API URL cleanup

docker-entrypoint-node.sh, rdrf/rdrf/frontend/package.json, rdrf/rdrf/frontend/src/app/app.unit.test.tsx, rdrf/rdrf/frontend/src/pages/proms_page/components/question.unit.test.tsx, rdrf/rdrf/frontend/src/setupTests.js, rdrf/rdrf/frontend/tsconfig.json, rdrf/rdrf/frontend/yarn.lock, travis-build.sh
PR combining `react_jest` and `rdrf-1738-react-scripts_update`, `react_jest` PR (#1730) no longer required.
=> RDRF #1718 & #1738 - react-scripts update & React testing

rdrf/rdrf/templates/admin/rdrf/commondataelement/change_form.html, rdrf/rdrf/templates/rdrf_cdes/base.html
- setDTypeVal previously called in document ready function to
correctly hide unneeded validators
- Used Django template functionality to create empty block
(morescripts)
- Moved setDTypeVal call to new defined morescripts block in
templates/admin/rdrf/commondataelement/change_form.html
=> RDRF #1779 Fixed setDTypeVal ReferenceError

rdrf/rdrf/helpers/utils.py, rdrf/rdrf/models/definition/models.py
- Added "eval" to the blacklist in contains_blacklisted_words
- Updated applicable_to methods of RegistryForm & ConsentSection
classes with exception handling on eval() usage and conditionals
to check if the applicability condition is valid before eval
=> rdrf #1859 Further hardened applicability condition evaluation

rdrf/rdrf/middleware.py, rdrf/rdrf/settings.py
If CSP is not enabled through environment variable - ENABLE_CSP=1
then the dummy csp middleware injects request.csp_nonce with an empty string.
=> rdrf #1874 dummy csp middleware added
