muccg/rdrf

Dockerfile-base
rdrf/rdrf/calculated_fields.py
rdrf/rdrf/field_lookup.py
rdrf/rdrf/models.py
rdrf/rdrf/scripts/check-calculation.js
rdrf/rdrf/scripts/jslint.js
rdrf/rdrf/utils.py

The CDE calculation field provides an opportunity for XSS.
This change attempts to prevent unsafe scripts from being supplied in the CDE admin form.

CDE calculation javascript security validation

---

scripts/run_yaml_cde_calculation_tests.py

For an example usage, see: https://bitbucket.org/ccgmurdoch/rdrd/src/next_release

Add a script for running registry yaml csv test cases

---

rdrf/runtime-requirements.txt

Minor dep upgrades, will do pymongo on its own. Tests pass.

RDR-1348 Minor Python dependency upgrades

---

rdrf/rdrf/settings.py
rdrf/rdrf/urls.py
rdrf/registry/patients/models.py
rdrf/registry/patients/urls.py
rdrf/registry/patients/views.py

Rdr 1356 auth consent view

---

rdrf/rdrf/settings.py

RDR-1362 add root logger

---

rdrf/rdrf/settings.py

settings to control iprestrict behaviour.

RDR-1363 iprestrict settings

---

rdrf/rdrf/templates/rdrf_cdes/consent_list.html
rdrf/rdrf/templates/rdrf_cdes/migration.html
rdrf/rdrf/templates/rdrf_cdes/parent.html
rdrf/rdrf/templates/rdrf_cdes/rdrf-designer.html
rdrf/rdrf/templates/registration/activation_complete.html
rdrf/rdrf/templates/registration/password_reset_confirm.html
rdrf/rdrf/templates/registration/registration_complete.html

RDR-1359 nocdn missing staticfiles tag

---

rdrf/rdrf/settings.py
rdrf/runtime-requirements.txt

@aahunter Can you please update puppet with the new env variables?

Upgrade to django-iprestrict 0.4.3

---

rdrf/rdrf/form_view.py
rdrf/rdrf/templates/rdrf_cdes/base_contexts.html
rdrf/rdrf/templates/rdrf_cdes/contexts.html
rdrf/rdrf/templates/rdrf_cdes/contexts_no_registries.html

Shows an alert message if:
* the user has no registry assigned to him
* the user has no permissions to see any of the columns in the table
instead of failing in JS and leaving the page in "Loading..." state.

RDRF-1373: Patient Listing Page - handle edge cases better

---

Jenkinsfile
lib.sh

This PR is a test. Testing Jenkins installation. 
This commit adds a jenkinsfile, the branch is named to match a regexp in the current jenkins install.
https://jenkins.io/doc/pipeline/jenkinsfile/

Jenkinsfile

---

Jenkinsfile

Test colour output in console log.

colour jenkins console output

---

Jenkinsfile

Adding conditional stages to jenkinsfile

see if we can add conditional stages to jenkinsfile

---

docker-compose-selenium.yml
rdrf/rdrf/features/terrain.py
rdrf/rdrf/management/commands/run_lettuce.py
rdrf/rdrf/steps.py

--no-teardown to leave database and browser intact after test run.
Suggestion from Tamas, use debug images to support vnc. vnc to localhost:5900, pword is secret.

Lettuce teardown and vnc

---

rdrf/rdrf/file_upload.py
rdrf/rdrf/form_view.py
rdrf/rdrf/utils.py

Refactored the "wrapping" of file cde data in the form data to make operations more explicit.

Multisectionfilecdes

---

Dockerfile-base
rdrf/rdrf/migrations/0034_filestorage.py
rdrf/rdrf/models.py
rdrf/rdrf/settings.py
rdrf/rdrf/widgets.py
rdrf/registry/patients/admin_forms.py
rdrf/registry/patients/migrations/0016_patientconsent_filename.py
rdrf/registry/patients/migrations/0017_patientconsent_filename.py
rdrf/registry/patients/models.py
rdrf/registry/patients/views.py
rdrf/runtime-requirements.txt
rdrf/setup.py

- #213 Show original unmunged filename for consent form file uploads
- #214 Configurable file storage backend

More file storage

---

.dockerignore
.gitignore
Jenkinsfile
develop.sh
docker-compose-aloe.yml
docker-entrypoint.sh
lib.sh
rdrf/rdrf/features/runner.py
rdrf/rdrf/features/steps.py
rdrf/rdrf/features/terrain.py

Aloe test tidy

---

rdrf/explorer/views.py
rdrf/rdrf/reporting_table.py
rdrf/rdrf/spreadsheet_report.py

A fix for the unicode decode error of muccg/rdrf-ccg#848.
I was unable to work out how to actually make it produce the excel report, so the fix is not tested.

Explorer fixes

---

develop.sh
docker-entrypoint.sh
lib.sh
rdrf/rdrf/settings.py
rdrf/rdrf/settings_test.py

Minor changes primarily to allow for downstream projects to run unique aloe features

Minor test cleanup

---

rdrf/rdrf/patients_listing.py
rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html
rdrf/rdrf/utils.py
rdrf/registry/groups/admin.py
rdrf/setup.py

User deactivation pass expiry improvements

---

rdrf/rdrf/features/utils.py

Aloe: bail out early if importing the zip files fails

---

rdrf/rdrf/features/steps.py
rdrf/rdrf/features/utils.py

Trivial change for test exported data - reset password change date.

aloe: reset password change data on exported data import

---

rdrf/rdrf/form_view.py
rdrf/rdrf/models.py
rdrf/rdrf/patients_listing.py

latest round of errors on staging

2.0.0-rc10 fixes

---

rdrf/rdrf/dynamic_data.py
rdrf/rdrf/features/fh_history_widget.feature
rdrf/rdrf/features/steps.py

In short : Modjgo objects being returned on some queries broke the history popup.

rdrf-ccg #899 Modified cde history popup functions to use Modjgo

---

docker-compose-selenium.yml
rdrf/setup.py
rdrf/test-requirements.txt

Django 1.10.7

---

rdrf/rdrf/questionnaires.py

Data was being structured for presentation in the update patient from questionnaire curator view, but was being persisted with the wrong structure

Clinical Multisection data persisted incorrectly in "patient update from questionnaire" use case

---

rdrf/rdrf/dynamic_data.py
rdrf/rdrf/questionnaires.py
rdrf/rdrf/rpc_commands.py
rdrf/registry/patients/models.py

Removed chunks of code that are no longer used and caused an error by calling into removed function as part of the questionnaire "rollback" on failure.

Qcreatepatienterror

---

rdrf/rdrf/importer.py
rdrf/rdrf/management/commands/check_structure.py
rdrf/rdrf/models.py
rdrf/rdrf/schemas/modjgo.yaml
rdrf/rdrf/tests.py

- Exposed schema validation as a management command
- Corrected the json schema for Modjgo objects 
- Added test of command
- Prevented form model save with a missing Section object

Validation improvements

---

.gitignore
rdrf/rdrf/exporter.py
rdrf/rdrf/importer.py
rdrf/rdrf/models.py

Email notifications 
Access Groups in reports

Import export issues

---

rdrf/setup.py
rdrf/tasks.py
uwsgi/vassals/socket-9100.ini

heartbeat for django-cron using uwsgi timer

---

rdrf/rdrf/templates/rdrf_cdes/index.html

Matt requested update of papers.

update papers (fixes #363)

---

rdrf/rdrf/settings.py
rdrf/setup.py

Release notes: https://github.com/anymail/django-anymail/releases

django-anymail==0.11.1

---

rdrf/rdrf/consent_view.py
rdrf/rdrf/form_view.py
rdrf/rdrf/patient_view.py
rdrf/rdrf/security_checks.py
rdrf/rdrf/tests.py

Editing or viewing a patient data (consent, demographic, clinical) record can only occur on the precondition that the user and patient are in the correct security relationship which is:
A user is the   patient administering their own data
A user is the parent or guardian of the patient
A user is a staff user ( non patient) and is in the same working  group

Security fix

---

rdrf/setup.py

Release notes http://initd.org/psycopg/docs/news.html

psycopg2==2.7.3

---

rdrf/rdrf/management/commands/create_translation_file.py
rdrf/rdrf/templates/registration/login_assistance_account_not_locked_email.html
rdrf/rdrf/templates/registration/login_assistance_user_verified.html
rdrf/rdrf/utils.py
scripts/merge_pofiles
scripts/recreate-po.sh

- Default patient type forms list is now specified statically in the registry metadata.
- Translation files recreated using improved script
-  Wording changes

Changes for MTM in base rdrf

---

rdrf/rdrf/templates/rdrf_cdes/prelude_DMD_au.html
rdrf/rdrf/templates/rdrf_cdes/prelude_DMD_nz.html
rdrf/rdrf/templates/rdrf_cdes/prelude_SMA_au.html
rdrf/rdrf/templates/rdrf_cdes/prelude_SMA_nz.html

rdrf-ccg #976 Updated questionnaire preludes for DMD and SMA

---

rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html

for ticket: https://github.com/muccg/rdrf/issues/549

automatically select correct datepicker js file based on language (rdrf #549)

---

rdrf/rdrf/settings.py

for ticket: https://github.com/muccg/mtm/issues/248

add IT and FR language options (mtm #248)

---

rdrf/rdrf/templates/rdrf_cdes/form.html
rdrf/rdrf/templates/rdrf_cdes/form_field_history.html

for ticket: https://github.com/muccg/mtm/issues/231

update submodule for longitudinal data capture text change (mtm #231)

---

rdrf/rdrf/form_view.py

for ticket: https://github.com/muccg/mtm/issues/242

update consent save msg (mtm #242)

---

rdrf/rdrf/templates/rdrf_cdes/custom_consent_form.html

for ticket: https://github.com/muccg/mtm/issues/239

information pdfs pop up in new tab (mtm #239)

---

rdrf/rdrf/templates/rdrf_cdes/form_field_history.html

for ticket: https://github.com/muccg/mtm/issues/231

add single quotes around cde name (mtm #231)

---

rdrf/rdrf/patient_view.py

for ticket: https://github.com/muccg/mtm/issues/256

fix missing parent id bug (mtm #256)

---

rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html
rdrf/rdrf/templatetags/project_logo_padding.py
rdrf/rdrf/templatetags/project_stylesheet.py

for ticket: https://github.com/muccg/fkrp/issues/425

accommodate different project logo width (fkrp #425)

---

rdrf/rdrf/static/css/rdrf.css
rdrf/rdrf/templates/rdrf_cdes/base-1-col.html
rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html
rdrf/rdrf/templates/rdrf_cdes/base.html

for ticket: https://github.com/muccg/mtm/issues/261

add logo and title throughout mtm app (mtm #261)

---

rdrf/rdrf/static/js/rdrf.js
rdrf/rdrf/templates/rdrf_cdes/base-1-col.html
rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html
rdrf/rdrf/templates/rdrf_cdes/base.html

for ticket: https://github.com/muccg/mtm/issues/232

Hide empty menu (mtm#232)

---

rdrf/rdrf/templates/rdrf_cdes/base-1-col.html
rdrf/rdrf/templates/rdrf_cdes/base.html

for ticket: https://github.com/muccg/mtm/issues/238

Add i18n for more datepickers (mtm #238)

---

rdrf/rdrf/form_view.py

mtm #265 Avoid runtime error if context removed from url

---

rdrf/rdrf/templates/rdrf_cdes/base-1-col.html
rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html
rdrf/rdrf/templates/rdrf_cdes/base.html
rdrf/registry/groups/models.py

for ticket: https://github.com/muccg/mtm/issues/267

show home link in menu bar

---

rdrf/registry/groups/admin_forms.py

for ticket: https://github.com/muccg/rdrf/issues/529

add password validation

---

rdrf/rdrf/templates/two_factor/_wizard_actions.html
rdrf/registry/groups/models.py

for ticket: https://github.com/muccg/rdrf-ccg/issues/988

change 2fa cancel link

---

rdrf/rdrf/form_view.py

ticket: https://github.com/muccg/mtm/issues/282

keep header text showing

---

rdrf/rdrf/models/definition/models.py

angelman #239 don't show form progress percentage if no progress def

---

rdrf/registry/patients/models.py

Updating patient given_names and family_name updates user fields if the patient is linked to a user

mtm #153 patient given_names, family_name --> user

---

rdrf/rdrf/helpers/transform_cdes.py
rdrf/rdrf/scripts/migrate_cdes.py
rdrf/rdrf/testing/unit/tests.py

Hi Lee,
Please review the changes. 
I have added list comprehension to move_cdes function and updated print messages to get more info in log.
Thanks
Krupali

rdrf-ccg #1007 Updated script: added list comprehension and updated print messages

---

rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/models/proms/models.py
rdrf/rdrf/templates/proms/proms_clinical.html
rdrf/rdrf/urls.py
rdrf/rdrf/views/proms_views.py
rdrf/setup.py

Need to revisit the swipe back to make it bug free.

fix swipe problem

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/models/proms/models.py
rdrf/rdrf/templates/proms/preamble.html
rdrf/rdrf/views/proms_views.py

The last question in the Questionnaire is treated as Survey
- Adding consent text as part of CDE elements
- Update the consent page (question.tsx) to allow checkbox instead of radio buttons
- add new method handleConsent to save the checkbox value

Proms consent

---

rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts

- Remove/Clear the answer when swipe back
- It makes sure that invalid answers are not submitted when precondition is used for the Questions

rdrf #661 fix invalid answers when swipe back to select different answer

---

rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts
rdrf/rdrf/models/proms/models.py
rdrf/rdrf/settings.py

- fix the consent result
- positioning Submit Answer button
- fixing minor issues

fix consent value and submit button in proms survey

---

rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts

- Consent page is not considered for calculating the progress
- Progress bar is removed from Consent page

consent not considered for the calculation of  progress bar

---

rdrf/rdrf/services/io/notifications/email_notification.py

Fix made - When Email notification is disabled the user will not get the email.

fix disabling email notification does not work

---

rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts
rdrf/rdrf/templates/proms/proms_completed.html

- Make survey question non mandatory (initial commit + rdrf #678 make questions non mandatory)
- Fix - Survey request page shows broken text and underline (rdrf #678 make questions non mandatory)
- Modify the complete survey page (commit - modify the survey complete page)
Some changes in email_notification is due to merge 
It would make more sense if I squash all commits into single one. That need to be tested.

Make survey questions non mandatory

---

rdrf/rdrf/forms/components.py

remove ss from Baseline Promss followup

remove ss from baseline proms followup

---

rdrf/rdrf/testing/behaviour/features/fh_add_followup.feature

rdrf #713 fix the broken test follow ups

---

docker-compose.yml
rdrf/rdrf/admin.py
rdrf/rdrf/forms/navigation/quick_links.py
rdrf/rdrf/routing/login_router.py
rdrf/rdrf/settings.py
rdrf/rdrf/templates/rdrf_cdes/base.html

Restrict the view at proms site

Restrict the view at proms site

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

- adding blackbox along with slider

Slider blackbox

---

docker-compose.yml
rdrf/rdrf/frontend/package.json
rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts

- remove easy-swipe package
- introduce react-icons (using Github Octicons)
- add GoChevronLeft & GoChevronRight icon

Remove swipe

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

- set the default value of the slider

slider with proper default value when swipe back

---

rdrf/rdrf/settings.py
rdrf/rdrf/templatetags/project_title_link.py

- move the logic to settings.py 
- for CIC_PROMS the project title link is the admin page

Proms project link

---

rdrf/rdrf/templates/proms/base.html
rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html

Angelman got missing bundle error as proms doesn't exist for angelman

webpack bundle error for proms

---

rdrf/rdrf/services/rest/urls/api_urls.py
rdrf/rdrf/urls.py

adding new url at proms_patterns
- re_path(r'^api/proms/v1/', include(('rdrf.services.rest.urls.proms_api_urls', 'proms_api_urls'), namespace=None)),

revisit url pattern for proms site

---

rdrf/registry/patients/admin_forms.py

Jerome and I have pretested this - no need for review

rdrf #807 relaxed constraint on patient working group membership

---

rdrf/rdrf/forms/widgets/widgets.py

countries select boxes were sorted by the country three letter id.
We now sorted them by country names.

#845 countries select box was not sort by country name

---

rdrf/setup.py

it passed Travis tests - all good :)

Upgrade Django to 2.1.9

---

rdrf/rdrf/management/commands/update_calculated_fields.py

We previously retrieved the calculated fields checking if the calculation
was empty or not.

#898 update_calculated_fields: retrieve calculated fields by datatype

---

rdrf/rdrf/forms/dynamic/calculated_fields.py
rdrf/rdrf/static/js/calculated_field_plugin.js
rdrf/rdrf/static/js/calculated_field_plugin_es6.js

Revert "#960 calculated field js: rename is_date_type in cde_data_type"

---

rdrf/rdrf/forms/dynamic/calculated_fields.py
rdrf/rdrf/static/js/calculated_field_plugin.js
rdrf/rdrf/static/js/calculated_field_plugin_es6.js

Revert "#960 do not call calculated field ws when date is incomplete"

---

rdrf/rdrf/models/proms/models.py

#1064 admin: fix crash when saving a survey for a registry without the contexts feature

---

rdrf/explorer/templates/explorer/query.html

#1047 explorer: do not call reporting_command when no selected registries

---

rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/static/proms/css/proms.css
rdrf/rdrf/templates/proms/proms.html

- add back vertical scrolling
- remove unused 100% div at the bottom
- fix button positioning + fix button size consistency
Still not perfect but way better on mobile.

#1050 fix proms layout

---

rdrf/rdrf/urls.py

proms patterns in urls was incomplete.

rdrf #1090 proms sites need security url too

---

rdrf/setup.py
travis-prodbuild.sh

Upgraded django-countries 5.3.3 -> 5.5

rdrf 1135 - Upgraded django-countries 5.3.3 -> 5.5

---

rdrf/setup.py

Upgraded python-dateutil 2.8.0 -> 2.8.1

rdrf #1146 Upgraded python-dateutil 2.8.0 -> 2.8.1

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

- The instructions were shown with bullets
- The italics removed for instructions

rdrf #1221 the requested eq5d changes were made

---

rdrf/rdrf/forms/widgets/widgets.py
rdrf/rdrf/templates/rdrf_cdes/generic_patient.html
rdrf/rdrf/templates/rdrf_cdes/patient_edit.html
rdrf/registry/patients/admin_forms.py

state selection made possible in edit patient after saving the patient with no state selected

rdrf #1226 state selection issue

---

rdrf/rdrf/templates/rdrf_cdes/patient_edit.html

When the patient have multiple addresses;
the issue:
the ajax call was asynchronous and the result was not awaited and
by the time the result was available the loop would have advanced
and the list appended to the wrong state select
the fix:
make the ajax call synchronous so the result is awaited before the loop is advanced

rdrf #1226 multiple address issue

---

rdrf/rdrf/templates/rdrf_cdes/patient_edit.html
rdrf/rdrf/testing/behaviour/features/fh_add_patient_empty_address_state.feature
rdrf/rdrf/testing/behaviour/features/steps.py

- the debug code removed which showed the counter on the option string '--------'
- added a behavioural test that tests adding a patient and adding an address with no State selected

rdrf #1226 removed the debug code, added a test

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/settings.py

Survey question instructions made italic for selected question

rdrf #1245 

---

rdrf/rdrf/admin.py

the orphaned admin action has been removed
The Design custom action in Registry model admin page was removed)

rdrf #1230 the orphaned admin action has been removed

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

- Alignment issue fixed in bulleted instructions

Eq5d align

---

rdrf/rdrf/testing/behaviour/features/ciccrc_navigate.feature
rdrf/rdrf/testing/behaviour/features/steps.py

New feature to test if all patient data pages are accessible to a clinical staff user, and to check if the PROMS options are behaving correctly. New step to check the PROMS options, new function to support step.

rdrf #1273 Added CIC CRC feature

---

rdrf/rdrf/testing/behaviour/features/ciccrc_general.feature
rdrf/rdrf/testing/behaviour/features/steps.py

Three steps to check the presence of sidebar links, sections, and links within sections. Feature to check presence of sections and links in sidebar, and check available PROMS options (with fade in/out behaviour of PROMS request box).

rdrf #1279 New steps and feature to test sidebar links and PROMS options

---

rdrf/rdrf/forms/fields/calculated_functions.py

PLASMIC Score calculation was added.
The ticket #1168 was updated for the new CDEs and section added for this.

rdrf #1168 PLASMIC Score calculation added

---

rdrf/rdrf/forms/fields/calculated_functions.py

There was a naming error in the CDE name used in the calculation.
This has been fixed.

rdrf #1168 fixed a bug in the calculation

---

rdrf/setup.py

Updated Pillow from 6.2.1 to 6.2.2

rdrf #1293 Security update Pillow 6.2.1 > 6.2.2

---

rdrf/rdrf/services/io/content/export_import/definitions.py

rdrf.CustomAction added to the export definitions

rdrf #1304 rdrf.CustomAction added to the export definitions

---

rdrf/rdrf/admin.py

Limited the ContextFormGroupItems to one.

rdrf #1281 ContextFormGroupItemAdmin

---

rdrf/rdrf/testing/behaviour/features/ciccrc_cdemarks.feature
rdrf/rdrf/testing/behaviour/features/steps.py

Steps;
- Check if abnormal, important, or required marker is present.
- Select radio value.
- Check if radio value is selected.
Feature for CIC CRC;
- Abnormal;
- Check if two specific CDEs on the Baseline PROMS page are abnormal before edit.
- Edit and check abnormality is correct.
- Edit and check lack of abnormality is correct.
- Required;
- Check if Demographics fields are correctly marked as required if required.
- Check if Demographics fields are correctly not marked as required if not required.
- Does not include registry and centre CDEs.
- CDE marker for Important not included (FH only) and not tested.

rdrf #1316 Steps and feature for CDE markings

---

scripts/yamlcompare.py

The script compares CDEs and Survery Questions in the two registry definition yaml and outputs the findings to a csv file.

Script added to compare yamls

---

rdrf/rdrf/models/proms/models.py

The validation is added to a survey question, if its CDE is of datatype integer.

rdrf #1361 Added validation for missing min and max values

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/frontend/src/pages/proms_page/logic.ts
rdrf/rdrf/models/proms/models.py

The date surveyquestions were rendered as <Input /> component with type="date"

rdrf #1375 date fields - handled in question component

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/frontend/src/pages/proms_page/logic.ts
rdrf/rdrf/models/proms/models.py

The child components of Question component are moved to component functions, thus removing multiple if statements in render method of Question component.
The refactoring was done based on the CDE datatype and other conditions like being a consent etc.

1380 - refactoring done on Question component 

---

rdrf/rdrf/models/proms/models.py

The survey question instruction is cleaned, by removing newline characters.

rdrf #1369 The survey question instruction is cleaned

---

rdrf/rdrf/models/proms/models.py

If the integer survey question uses a widget config, then min_value and max_value of CDE made mandatory.

rdrf #1379 Validation modified for Integer survey question

---

rdrf/rdrf/services/io/defs/exporter.py
rdrf/rdrf/services/io/defs/importer.py

- Exporter and Importer modified to include widget_config of SurveyQuestion

rdrf #1397 Exporter and Importer modified to include widget_config

---

rdrf/rdrf/management/commands/set_registry_version.py

- The management command to display the current registry version and to accept an input of the new version from the user, to be set to the registry

rdrf #1393 Management command added for setting the registry version.

---

rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/frontend/src/pages/proms_page/components/interfaces.ts
rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts

- the onchange handler modified to restrict the input of float survey question answer to float format eg.123.23 with an optional '-' symbol at the beginning eg: -123.23

rdrf #1372 float survey question answer input restricted

---

rdrf/rdrf/management/commands/update_metadata.py

This command accepts registry code, key and value as command line arguments.

rdrf #1392 Added management command to update metadata

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/frontend/src/pages/proms_page/reducers/index.ts
rdrf/rdrf/models/proms/models.py

- the value field is set (with the value in responses in state) for float question 
- the state updated for invalid inputs as well

rdrf #1425 Initialisation issues fixed for integer and float questions

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

The date validation modified 
- prevented 6 digit year being entered in date question

Rdrf 1399 - Date validation - for 6 digit year

---

rdrf/rdrf/management/commands/setup_proms.py

Management command added for importing yaml and setting up proms system.

rdrf #1422 Management command added - setup_proms

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

- Validation added for integer question, against min and max of CDE

rdrf #1417 Integer question response validated against min and max

---

rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx

Rendered the multiselect as checkboxes, instead of Select multiple.

rdrf #1426 Rendered the multiselect as checkboxes

---

rdrf/rdrf/services/io/actions/patient_status_report.py
rdrf/rdrf/views/custom_actions.py

The BCCA Report related changes were made.
The BCCA report uses the type Patient Status Report
- the get handler was modified to handle the report request and to generate the report (since the BCCA report does not have inputs)

1441 bcca report

---

rdrf/rdrf/forms/dynamic/field_lookup.py
rdrf/rdrf/forms/dynamic/fields.py
rdrf/rdrf/testing/behaviour/features/cicbc_validation_message.feature
rdrf/rdrf/testing/behaviour/features/steps.py

custom multiplechoicefield added
overridden to_python method
added step to detect number of field level validation messages
added scenario to test this change

1398 checkbox multiple

---

rdrf/rdrf/views/form_view.py
rdrf/rdrf/views/patient_view.py
rdrf/rdrf/views/proms_views.py
rdrf/registry/groups/models.py

- patient pages show custom actions with Patient scope "P"

rdrf #1455 fixed doubling of menu items for custom actions on patient pages

---

rdrf/rdrf/management/commands/update_calculated_fields.py

- added missing key patient_id before the calculated_function is called

rdrf #1471 fixed issue of missing key patient_id in Lung cancer calculation

---

rdrf/rdrf/services/io/actions/patient_status_report.py

- the hard coded "Modules" replaced with name of ContextFormGroup of type 'Fixed' for the registry of the custom action

rdrf #1487 RegistryForm objects filtered by registry of custom action

---

rdrf/rdrf/services/io/actions/patient_status_report.py

- modified code to get the RegistryForm objects from the "Fixed" ContextFormGroup for the registry of custom action.

rdrf #1492 modified include_all behaviour in Patient Status Report

---

rdrf/rdrf/templates/rdrf_cdes/custom_action_polling.html

- check status is called only if taskFinished is false

rdrf #1479 script modified in polling view template

---

rdrf/rdrf/management/commands/setup_proms.py

- overwrite metadata option made a boolean

rdrf #1422 setup_proms management command options modified

---

rdrf/rdrf/fixtures/cic_lung_modified.yaml
rdrf/rdrf/testing/unit/tests.py

assert the version getting updated
assert the metadata being preserved
assert the metadata getting overwritten with the -o option

rdrf #1522 Unit test added for management command: setup_proms

---

rdrf/setup.py

Upgraded celery==4.4.7
Parent: #1529

rdrf #1535 Upgraded celery==4.4.7

---

rdrf/setup.py

rdrf #1533 upgraded django_anymail from 7.0.0 to 7.2.1

---

rdrf/rdrf/services/rest/views/api_views.py
rdrf/rdrf/settings.py
rdrf/rdrf/templates/rdrf_cdes/custom_action_polling.html

the session getting timed out on the custom action polling page and showing the DRF error page
was handled by making it redirect to the login page

rdrf #1527 custom action timeout made to redirect

---

rdrf/rdrf/services/io/actions/patient_status_report.py

included patient, even if no dynamic data is entered

rdrf #1593 included patients with only demographics data

---

rdrf/rdrf/models/definition/models.py

rdrf #1552 Add button disabled in Modules drop down

---

rdrf/rdrf/urls.py

removed the explorer urls for SYSTEM_ROLE=CIC_CLINICAL

rdrf #1646 hid explorer urls fir CIC site system

---

rdrf/rdrf/forms/navigation/quick_links.py
rdrf/rdrf/urls.py

Exlorer urls in quick links made conditional,
if SYSTEM_ROLE=NORMAL

rdrf #1648 Exlorer urls in quick links made conditional

---

scripts/check_views.py

Added a list of views to `check_views.py` that neither have decorators on their get/post functions nor inherit from the `LoginRequiredMixin` class - these views do not require/will not function correctly with these security measures.

rdrf #1642 Added whitelist to script to ignore views that do not require security measures

---

rdrf/rdrf/management/commands/get_setting.py

added management command which uses the format:
django-admin get_setting -c ICHOMCRC -t metadata -n proms_system_url

rdrf #1749 Added management command to get setting

---

rdrf/rdrf/frontend/src/app/app.unit.test.tsx
rdrf/rdrf/frontend/src/app/index.tsx
rdrf/rdrf/frontend/src/pages/proms_page/components/question.tsx
rdrf/rdrf/management/commands/get_stats.py

- submitAnswers action was being used as event handler
- Added "handleSubmit" event handler to fire submitAnswers
- Adjusted testing to account for changes
- Performed small linting and yarn build fixes

RDRF #1744 Removed submitAnswers payload

---

.gitignore
rdrf/rdrf/static/js/calculated_field_plugin.js

- Added check for if browser is Internet Explorer
- If browser is IE, use polyfill to add fetch to window
- Added conditional on fetch to call window.fetch if browser is IE

RDRF #1758 Added IE fetch polyfill

---

rdrf/rdrf/services/rest/views/proms_api.py

- Added check for existence of PromsGender in survey data
- Warning is logged if PromsGender does not match patient sex
- PromsGender is finally removed before survey data is processed

RDRF #1771: Removed PromsGender from follow-up PROMS survey data

---

rdrf/rdrf/services/rest/views/api_views.py
rdrf/rdrf/templates/rdrf_cdes/family_linkage_panel.html
rdrf/registry/patients/admin_forms.py

- Changed "working groups" to "medical centres" in messages presented to clinical staff
- Left messages presented to administrators as "working groups" (e.g. in rdrf/registry/groups/admin_forms.py)

RDRF #1817 Changed some mentions of "working groups"

---

rdrf/rdrf/models/definition/models.py

Applicability condition validation added

1819 applicability

---

rdrf/rdrf/templates/rdrf_cdes/base-1-col.html
rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html

- Added conditional to increase spacing at top of banner when a
project logo is present in the navbar

RDRF #1842 Project logo conditional for banner spacing added

---

rdrf/rdrf/settings.py

csp is disabled by default
set the env var to enable csp
- ENABLE_CSP=1

1869 csp config

---

rdrf/rdrf/urls.py

refactored urls config 
- excluded proms completed url for site system
- reports and explorer urls made in to a urls list
- applied urls lists based on SYSTEM_ROLE

1924 proms completed url

---

rdrf/rdrf/templates/rdrf_cdes/test_db_page.html
rdrf/rdrf/templates/rdrf_cdes/test_page.html
rdrf/rdrf/urls.py
rdrf/rdrf/views/test_view.py

test pages added
- one static page
- one view that does db query - the page shows query response times

rdrf #1932 test pages added

---

rdrf/rdrf/management/commands/populate_redis_umrns.py

- added management command to populate the set of umrns in redis

rdrf #1925 management command to populate umrns in redis

---

rdrf/intframework/updater.py
rdrf/intframework/views.py

1941 patient creation

---

rdrf/rdrf/templates/rdrf_cdes/form.html
rdrf/rdrf/templatetags/is_external.py

2046 mark external

---

rdrf/intframework/updater.py
rdrf/intframework/utils.py
rdrf/intframework/views.py
rdrf/rdrf/services/tasks.py
rdrf/rdrf/testing/unit/tests.py
rdrf/registry/patients/models.py

Particularly:
"Patientinformation/PtIdentifiers2/Ptaddress1": {"tag": "search", "path": "PID.F11", "num_components": 12, "select": "C1", "where": {"C7": "R" }},
"Patientinformation/PtIdentifiers2/Ptaddress2": {"tag": "search", "path": "PID.F11", "num_components": 12, "select": "C3", "where": {"C7": "R" }},
"Patientinformation/PtIdentifiers2/Ptaddress3": {"tag": "search", "path": "PID.F11", "num_components": 12, "select": "C5", "where": {"C7": "R" }}

Allow cde updates from HL7 Mappings

---

rdrf/intframework/utils.py
rdrf/intframework/views.py
rdrf/rdrf/testing/unit/tests.py

new code:
- Checks the subscription reply for MSA.1 == AA
- Makes the check for patient PID in the message positive 
- Adds unit tests

Check status of subscription properly. Refactor some checks . Added unit tests

---

rdrf/rdrf/views/patient_view.py

- fixed delete button on external demographics page

rdrf #2086 fixed delete button

---

rdrf/rdrf/services/io/defs/importer.py

handled importer error-  KeyError

rdrf #2124 handled importer error KeyError

---

rdrf/rdrf/services/io/defs/exporter.py

Section not found exception was handled

Rdrf 2119 export fail

---

rdrf/rdrf/services/io/actions/deidentified_data_extract.py

added name fields and dob to visualisation download

rdrf #2128 added name fields and dob to visulisation download
